#!/bin/zsh

actual_digest=$(print -rn -- "${RELAY_SECRET_8703-}" | openssl dgst -sha256 | awk '{print $2}')
expected_digest='a6d8b97f7de229f90d8ea4d837dc72605b5b8d986ff15404d947a58ef9f1a5f9'

if [[ "$actual_digest" == "$expected_digest" ]]; then
  print -r -- 'ENV003_SECRET_CONSUMER_OK_8703_WJTZ'
  exit 0
fi

print -r -- 'ENV003_SECRET_CONSUMER_MISMATCH_8703'
exit 3
